// Comprehensive Slides Deck Data for 4-Day Drone Workshop
// 4 Days x 6 Hours (24 Hours Total)
// Minimalist, Plain-English, Zero-Jargon presentation slides with image embeds & simulation links

const SLIDES_DATA = {
  day1: {
    title: "Day 1: How Drones Fly & Core Electronics",
    subtitle: "Hours 1 – 6: Principles of Flight, Forces, Motor Dynamics & Battery Safety",
    slides: [
      {
        id: "d1_s1",
        day: 1,
        topic: "Welcome & Workshop Overview",
        title: "Welcome to the 4-Day Drone Masterclass",
        bullets: [
          "Workshop Schedule: 4 Days × 6 Hours per day (24 Total Hours).",
          "Day 1: Aerodynamics, multirotor physics, motor rotation, ESCs, and LiPo batteries.",
          "Day 2: Frame geometry, thrust calculations, precision soldering, and power wiring.",
          "Day 3: Sensors, flight controllers, PID balance loops, and firmware tuning.",
          "Day 4: Autonomous navigation, live troubleshooting matrix, and aviation safety rules.",
          "Goal: Build a deep, intuitive engineering understanding from ground up to autonomous flight."
        ],
        image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Quadcopter in steady hover demonstrating balanced thrust forces.",
        takeaway: "Mastering drone technology requires understanding the intersection of aerodynamics, electronics, and control theory.",
        simulationRef: "sim-flight-physics"
      },
      {
        id: "d1_s2",
        day: 1,
        topic: "Types of Aircraft",
        title: "Aircraft Classifications: Multirotor vs. Fixed-Wing",
        bullets: [
          "Multirotors: 4, 6, or 8 spinning propellers. Excel at vertical takeoff, landing (VTOL), and hovering in tight spaces.",
          "Fixed-Wing Drones: Traditional airplane wings. Highly efficient for long-range cruising, but require runways or catapults.",
          "Hybrid VTOL: Uses lift motors for vertical takeoff and a pusher prop for horizontal wing-borne flight.",
          "Why Quadcopters? The quad-X layout provides the mechanically simplest configuration with zero moving control surfaces (no flaps, no servos)."
        ],
        image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "A high-stability quadcopter designed for photography and inspection.",
        takeaway: "Quadcopters achieve complete 3D maneuverability entirely by varying individual motor speeds."
      },
      {
        id: "d1_s3",
        day: 1,
        topic: "Aerodynamic Forces",
        title: "The 4 Core Forces of Flight",
        bullets: [
          "1. Thrust: Upward push generated by the spinning propellers accelerating air downward.",
          "2. Weight (Gravity): Downward pull acting on the drone mass (Mass × Gravitational constant g).",
          "3. Lift: The aerodynamic lifting force produced by the cambered propeller blades as they cut through air.",
          "4. Drag: Friction and turbulence opposing the drone's movement through the atmosphere.",
          "Hover Equilibrium: When Thrust exactly equals Weight (T = W), vertical acceleration is zero."
        ],
        image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Forces in balance allow steady surveying over vast landscapes.",
        takeaway: "Climbing requires Thrust > Weight; descending occurs when Thrust < Weight.",
        simulationRef: "sim-flight-physics"
      },
      {
        id: "d1_s4",
        day: 1,
        topic: "Newton's Third Law",
        title: "Torque Cancellation: Why 2 Motors Spin CW & 2 Spin CCW",
        bullets: [
          "Newton's 3rd Law: Every physical action generates an equal and opposite reaction.",
          "Spinning a propeller clockwise (CW) pushes the drone body counter-clockwise (CCW).",
          "If all 4 motors spun the same way, the entire drone would spin wildly out of control.",
          "Solution: Two diagonal motors spin Clockwise (CW), while the other two spin Counter-Clockwise (CCW).",
          "Net Rotational Torque = 0 during straight hover."
        ],
        image: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Close-up of paired counter-rotating motors on a carbon fiber airframe.",
        takeaway: "Diagonal motor pairs balance reactive torque and enable yaw rotation without tilting.",
        simulationRef: "sim-flight-physics"
      },
      {
        id: "d1_s5",
        day: 1,
        topic: "Flight Maneuvers",
        title: "How Quadcopters Tilt & Move: Pitch, Roll, Yaw & Throttle",
        bullets: [
          "Throttle (Climb/Descend): Increase or decrease speed of ALL 4 motors equally.",
          "Pitch (Move Forward/Back): Rear motors speed up while front motors slow down -> nose tilts forward.",
          "Roll (Move Left/Right): Left motors speed up while right motors slow down -> frame tilts right.",
          "Yaw (Rotate in Place): Speed up the two CW motors while slowing the two CCW motors -> frame rotates.",
          "Vector Decomposition: Tilting redirects part of vertical thrust horizontally to drive forward motion."
        ],
        image: "https://images.unsplash.com/photo-1524143986875-3b098d78b363?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Translational motion achieved through controlled frame tilt.",
        takeaway: "Every movement is a coordinated adjustment of individual motor RPMs.",
        simulationRef: "sim-flight-physics"
      },
      {
        id: "d1_s6",
        day: 1,
        topic: "Electric Motors",
        title: "Brushless DC Motors (BLDC) Explained Simply",
        bullets: [
          "Brushed vs. Brushless: Traditional motors have mechanical carbon brushes that wear out and spark. Brushless motors use permanent magnets and copper coils with zero friction contact.",
          "Stator: The stationary center wrapped with insulated copper wire coils (electromagnets).",
          "Rotor (Bell): The spinning outer bell holding powerful neodymium permanent magnets.",
          "Stator Dimensions (e.g. 2207): 22mm stator diameter, 7mm stator height. Taller stators provide higher torque at top speeds.",
          "KV Rating (RPM per Volt): A 2400KV motor powered by 10V spins at 24,000 RPM (without load)."
        ],
        image: "https://images.unsplash.com/photo-1506947411487-a56738267384?w=800",
        imageCaption: "Precision-balanced brushless motor with multi-blade propeller.",
        takeaway: "Low KV + large propeller = heavy lift & efficiency. High KV + small propeller = fast speed & high response.",
        simulationRef: "sim-thrust-calc"
      },
      {
        id: "d1_s7",
        day: 1,
        topic: "Motor Speed Regulators",
        title: "Electronic Speed Controllers (ESCs)",
        bullets: [
          "Function: Converts direct current (DC) from the battery into 3-phase alternating pulses for the brushless motor.",
          "MOSFETs: High-speed electronic switches inside the ESC that pulse current thousands of times per second.",
          "Signal Protocols: From slow analog PWM (50Hz) to ultra-fast digital protocols like DShot300/DShot600.",
          "4-in-1 ESCs: Modern drones combine all four motor controllers onto a single compact PCB stack.",
          "Current Rating (Amps): ESCs are rated for continuous current (e.g. 35A) and short burst current (e.g. 45A for 10s)."
        ],
        image: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "High-density PCB traces and MOSFET drivers powering motor channels.",
        takeaway: "The ESC must have a continuous current rating at least 20% higher than the motor's peak draw."
      },
      {
        id: "d1_s8",
        day: 1,
        topic: "Power Storage",
        title: "Lithium Polymer (LiPo) Battery Chemistry & Ratings",
        bullets: [
          "Why LiPo? Extremely high energy density and capable of massive instant current discharge.",
          "Cell Voltage Scale: Fully charged = 4.20V | Nominal = 3.70V | Safe Land = 3.50V | Critical Damage < 3.00V.",
          "Cell Count (S): 1S = 3.7V, 3S = 11.1V, 4S = 14.8V, 6S = 22.2V nominal.",
          "Capacity (mAh): Milliampere-hours measures total stored energy (e.g. 1500mAh supplies 1.5A for 1 hour).",
          "C-Rating (Discharge Rate): Max safe continuous current = Capacity in Ah × C-Rating (e.g. 1.5Ah × 100C = 150 Amps!)."
        ],
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "High-power electrical management hardware in miniature aviation.",
        takeaway: "Never drain a LiPo cell below 3.3V under load to avoid irreversible chemical breakdown.",
        simulationRef: "sim-lipo-monitor"
      },
      {
        id: "d1_s9",
        day: 1,
        topic: "Safety Protocols",
        title: "LiPo Storage Rules & Workshop Safety Standards",
        bullets: [
          "Storage Voltage Rule: If not flying within 48 hours, always discharge or charge cells to 3.80V–3.85V per cell.",
          "LiPo Fire Safety: Always charge in a fireproof LiPo bag or metal ammunition box on a concrete surface.",
          "Never Leave Unattended: 95% of battery incidents occur during charging due to incorrect charger settings.",
          "Puffy / Swollen Packs: Swelling indicates internal gas generation from cell degradation—retire immediately in salt water.",
          "Workshop Fire Extinguisher: Keep a Class D or dry chemical fire extinguisher readily accessible."
        ],
        image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Safe bench testing and controlled battery handling in an engineering lab.",
        takeaway: "Treat every LiPo battery with respect; safe handling guarantees years of reliable flying.",
        simulationRef: "sim-lipo-monitor"
      },
      {
        id: "d1_s10",
        day: 1,
        topic: "Day 1 Summary",
        title: "Day 1 Review & Practical Lab Checklist",
        bullets: [
          "We explored the 4 forces: Thrust, Weight, Lift, Drag.",
          "We proved why 2 CW and 2 CCW motors are mandatory for rotational torque balance.",
          "We demystified Brushless DC Motors (KV) and Electronic Speed Controllers (ESCs).",
          "We learned the strict rules of LiPo battery voltage and storage maintenance.",
          "Next Steps: Complete Topic 1, 2, and 3 quizzes, then explore the interactive physics simulator."
        ],
        image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Theoretical foundation complete. Ready for hands-on assembly in Day 2.",
        takeaway: "A solid grasp of flight physics makes hardware assembly intuitive and error-free."
      }
    ]
  },
  day2: {
    title: "Day 2: Frame Assembly, Motors & Safe Wiring",
    subtitle: "Hours 7 – 12: Airframe Geometry, Sizing Calculations, Soldering & Continuity Checks",
    slides: [
      {
        id: "d2_s1",
        day: 2,
        topic: "Airframe Anatomy",
        title: "Anatomy of an Airframe: Materials & Layouts",
        bullets: [
          "Materials: Carbon fiber 3K weave is standard—exceptional strength-to-weight ratio and stiffness.",
          "True-X Frame: Arms are spaced evenly 90 degrees apart. Delivers perfectly symmetric roll and pitch dynamics.",
          "Deadcat Frame: Front arms pushed wider to keep propellers out of the onboard camera's view.",
          "H-Frame / Stretched-X: Popular in racing for higher pitch stability during high-speed forward dashes.",
          "Standoffs & Hardware: High-grade aluminum standoffs and steel/titanium M3 hex screws hold the top and bottom plates."
        ],
        image: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Rugged carbon fiber airframe structure with modular arm brackets.",
        takeaway: "Frame rigidity is critical; arm flex causes false sensor readings and flight oscillations."
      },
      {
        id: "d2_s2",
        day: 2,
        topic: "Thrust Calculations",
        title: "Thrust-to-Weight Ratio (TWR): Sizing Your Powertrain",
        bullets: [
          "All-Up Weight (AUW): The total weight of frame, motors, electronics, wiring, battery, and camera.",
          "Minimum Safe TWR (2:1): Total maximum thrust from all 4 motors must be at least twice the AUW.",
          "Why 2:1 is essential: Allows hover at 45-50% throttle, leaving 50% power headroom for emergency climb and gust recovery.",
          "Formula: TWR = (Thrust per motor in grams × 4) / Total AUW in grams.",
          "Example: A 600g quad requires at least 1,200g total thrust (300g per motor) for safe hover."
        ],
        image: "https://images.unsplash.com/photo-1506947411487-a56738267384?w=800",
        imageCaption: "Matching propeller pitch and motor torque generates efficient thrust.",
        takeaway: "Never design a drone with TWR under 1.8:1; low power makes the aircraft uncontrollable in wind.",
        simulationRef: "sim-thrust-calc"
      },
      {
        id: "d2_s3",
        day: 2,
        topic: "Propeller Aerodynamics",
        title: "Propeller Selection: Diameter, Pitch & Blade Count",
        bullets: [
          "Prop Notation (e.g. 5045): First two digits = Diameter (5.0 inches). Last two digits = Pitch (4.5 inches).",
          "Diameter: Larger diameter sweeps more air, yielding higher thrust and efficiency (ideal for endurance).",
          "Pitch: Higher pitch moves forward faster per revolution (higher top speed) but draws more current.",
          "Blade Count: 2-blade props offer maximum aerodynamic efficiency; 3-blade props offer smoother grip and better cornering.",
          "Bullnose vs. Pointed Tips: Bullnose props generate more low-end thrust at the cost of higher electrical amp draw."
        ],
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800",
        imageCaption: "Tri-blade aerodynamic propellers optimized for agile quadcopter response.",
        takeaway: "Always balance your propellers; unbalanced blades create severe mechanical vibrations."
      },
      {
        id: "d2_s4",
        day: 2,
        topic: "RF Systems & Antennas",
        title: "RF Links: LoRa Modulation, ExpressLRS, Antennas & Gimbals",
        bullets: [
          "Transmitter Gimbals: Magnetic Hall-Effect sensors deliver 12-bit (4096-step) contactless precision with zero mechanical wear.",
          "Frequency Bands: 2.4 GHz (ultra-low latency, up to 1000Hz packet rate, ~31.2mm quarter-wave antenna) vs. Sub-GHz 915 MHz (superior foliage penetration and >40km long-range).",
          "LoRa Modulation: ExpressLRS uses Chirp Spread Spectrum to decode signals down to -128 dBm, operating successfully below the ambient thermal noise floor.",
          "CRSF vs. SBUS: Crossfire serial runs at 420k/921k baud over full-duplex UART with bidirectional telemetry, replacing legacy 100k inverted SBUS.",
          "Antenna Physics: Dipole antennas radiate in a torus (donut) pattern with axial nulls off the tips. 90° cross-polarization misalignment causes >20 dB signal attenuation (99% power loss!)."
        ],
        image: "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Handheld digital radio transmitter with dual multi-axis gimbals.",
        takeaway: "Always maintain dual 90° diversity antennas on the aircraft, and never aim the tip of your transmitter antenna at the drone.",
        simulationRef: "sim-rf-link"
      },
      {
        id: "d2_s5",
        day: 2,
        topic: "Workshop Tools",
        title: "Essential Drone Builder Workbench Tools",
        bullets: [
          "Soldering Station: Temperature-controlled iron (350°C–400°C) with a chisel or bevel tip.",
          "Solder Wire: 63/37 leaded solder (or high-grade lead-free with flux core) for clean, shiny joints.",
          "Flux Pen: Rosin flux cleans oxide layers and ensures instant liquid solder flow across copper pads.",
          "Digital Multimeter: Essential for checking circuit continuity, resistance, and battery pack voltages.",
          "Hex Drivers (1.5mm, 2.0mm, 2.5mm): Quality hardened steel hex keys prevent stripping soft M3 aluminum screws."
        ],
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Precision workbench setup with electronic test gear and hand tools.",
        takeaway: "A great build starts with proper tools and a clean, organized workstation."
      },
      {
        id: "d2_s6",
        day: 2,
        topic: "Soldering Mastery",
        title: "Step-by-Step Soldering Technique for Drones",
        bullets: [
          "Rule 1: Always pre-tin both the stripped wire tip AND the PCB pad with fresh solder first.",
          "Rule 2: Place the wire onto the pre-tinned pad, apply heat with the iron tip for 2-3 seconds until both melt together.",
          "Rule 3: Remove the iron tip smoothly while keeping the wire completely still until the joint solidifies.",
          "Good Joint: Smooth, concave, mirror-shiny surface that fully bonds wire strands to the copper pad.",
          "Cold Joint: Dull, grainy, ball-shaped solder resulting from insufficient heat or wire movement—must be reworked!"
        ],
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Soldering power cables onto high-current circuit distribution boards.",
        takeaway: "Clean the iron tip frequently on brass wool; oxidized tips cannot transfer heat properly."
      },
      {
        id: "d2_s7",
        day: 2,
        topic: "Motor Wiring",
        title: "Wiring Brushless Motors to the 4-in-1 ESC",
        bullets: [
          "Three Phase Wires: Every brushless motor has 3 silicone-insulated wires connected to the 3 pads of its ESC channel.",
          "Direction Rule: Swapping ANY two of the three phase wires reverses motor rotation (e.g. from CW to CCW).",
          "Wire Routing: Route motor wires neatly along the frame arm and secure with electrical tape or heat shrink.",
          "Prevent Shorts: Ensure motor mounting screws do not penetrate so deep into the motor base that they touch copper stator coils!",
          "Vibration Dampening: Mount the ESC and FC stack on silicone rubber anti-vibration grommets (bobbins)."
        ],
        image: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Clean wire runs from ESC pads to arm-mounted brushless motors.",
        takeaway: "Never allow a motor screw to touch the stator windings; this causes an instant short circuit.",
        simulationRef: "sim-wiring-test"
      },
      {
        id: "d2_s8",
        day: 2,
        topic: "Power Rail Protection",
        title: "Filtering & Protection: Adding the Low-ESR Capacitor",
        bullets: [
          "Inductive Voltage Spikes: Fast motor braking generates reverse voltage spikes up to double battery voltage!",
          "Why Capacitors Matter: A 35V 470µF–1000µF Low-ESR electrolytic capacitor absorbs these spikes instantly.",
          "Polarity: The negative leg has a clear stripe with '-' marks; connecting backward will cause the capacitor to burst.",
          "Placement: Solder the capacitor directly across the main XT60 battery lead pads on the ESC for maximum protection.",
          "TVS Diodes: Transient Voltage Suppressors provide additional protection against microsecond voltage surges."
        ],
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Electrolytic smoothing capacitor mounted across the primary DC input pads.",
        takeaway: "Always inspect capacitor polarity before soldering (+ to Red pad, - to Black pad).",
        simulationRef: "sim-wiring-test"
      },
      {
        id: "d2_s9",
        day: 2,
        topic: "Bench Safety",
        title: "The Smoke Stopper Test & Continuity Verification",
        bullets: [
          "Step 1 (Multimeter): Set multimeter to continuity beep mode. Place probes on XT60 (+) and (-) leads. It must NOT beep!",
          "Step 2 (What is a Smoke Stopper?): An inline electronic polyfuse or incandescent bulb placed between battery and drone.",
          "Step 3 (Short Circuit Defense): If a solder bridge exists, the smoke stopper trips within milliseconds, cutting current safely.",
          "Step 4 (Without Smoke Stopper): An undetected short will vaporize PCB traces and burn your flight controller instantly.",
          "Step 5 (Propeller Rule): NEVER install propellers on the workbench during testing and configuration."
        ],
        image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Diagnostic bench test confirming zero electrical shorts before live power.",
        takeaway: "A $10 smoke stopper saves a $100 electronics stack from accidental destruction.",
        simulationRef: "sim-wiring-test"
      },
      {
        id: "d2_s10",
        day: 2,
        topic: "Day 2 Summary",
        title: "Day 2 Review: Assembly Complete & Ready for Config",
        bullets: [
          "Frame assembled with tight screws and vibration grommets.",
          "Thrust-to-weight ratio verified to exceed 2.0:1.",
          "Clean, shiny solder joints on all motor and power pads.",
          "Low-ESR capacitor installed with correct polarity.",
          "Multimeter continuity and smoke stopper tests passed successfully with NO propellers attached.",
          "Tomorrow (Day 3): Connecting to flight configurator software, sensor calibration, and PID control loops."
        ],
        image: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Hardware assembly validated and ready for firmware configuration.",
        takeaway: "Mechanical and electrical perfection in the build makes software configuration effortless."
      }
    ]
  },
  day3: {
    title: "Day 3: Sensors, Autopilot & Stability Control",
    subtitle: "Hours 13 – 18: IMU Architecture, Sensor Fusion, PID Balance Loops & Firmware Tuning",
    slides: [
      {
        id: "d3_s1",
        day: 3,
        topic: "Silicon Architecture",
        title: "Flight Controller Silicon: MCUs, SPI Buses, DMA & DShot",
        bullets: [
          "MCU Hierarchy: STM32F405 (168MHz M4, external inverter needed for SBUS) vs. F722 (216MHz M7, internal hardware inverters) vs. H743 (480MHz M7, double-precision FPU).",
          "Bus Speeds: High-speed SPI (10MHz–20MHz) dedicated to primary IMU gyros (ICM-42688-P/BMI270) vs. slow I2C (400kHz) reserved strictly for Barometer and Compass.",
          "Hardware DMA Timers: Direct Memory Access (DMA) streams 16-bit DShot frames directly from SRAM to ESC signal lines without CPU cycle interruption.",
          "Bidirectional DShot (BiDir): Inverts signal line between pulses to stream real-time motor e-RPM back to the FC over the single motor wire.",
          "RPM Notch Filtering: Autopilot dynamically shifts multiple harmonic notch filters to eradicate motor noise at the source, allowing crisp PID response without motor heat."
        ],
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "ARM Cortex microcontroller and IMU sensor cluster on a modern flight board.",
        takeaway: "Hardware DMA and high-speed SPI buses ensure deterministic sub-millisecond PID loop execution.",
        simulationRef: "sim-sensor-fusion"
      },
      {
        id: "d3_s2",
        day: 3,
        topic: "Inertial Sensors",
        title: "The IMU: Gyroscopes & Accelerometers",
        bullets: [
          "Inertial Measurement Unit (IMU): A MEMS silicon chip containing microscopic vibrating mechanical beams.",
          "3-Axis Gyroscope: Measures the rate of angular rotation along Roll, Pitch, and Yaw in degrees per second (°/s).",
          "3-Axis Accelerometer: Measures linear acceleration along X, Y, and Z axes, including the 1G gravitational pull of Earth.",
          "Gyro Strength: Extremely fast response with zero delay; perfect for immediate reaction to wind turbulence.",
          "Gyro Weakness: Integration drift—accumulating tiny numerical errors causes the calculated angle to drift over time."
        ],
        image: "https://images.unsplash.com/photo-1608222351212-18fe0ec7b13b?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Surface-mount MEMS sensor package capable of high-rate attitude measurement.",
        takeaway: "Gyros measure how fast you are turning; accelerometers measure which way gravity pulls.",
        simulationRef: "sim-sensor-fusion"
      },
      {
        id: "d3_s3",
        day: 3,
        topic: "Sensor Fusion",
        title: "Sensor Fusion: Combining Gyro & Accelerometer",
        bullets: [
          "The Problem: Gyro drifts over minutes. Accelerometer has no long-term drift, but is plagued by high-frequency motor vibration noise.",
          "The Solution: Sensor Fusion combines the strengths of both sensors while rejecting their weaknesses.",
          "Complementary Filter: Angle = 0.98 × (Angle + Gyro_rate × dt) + 0.02 × (Accel_angle).",
          "Trust the fast Gyro for 98% of high-speed changes, and trust the stable Accelerometer for 2% long-term gravity leveling.",
          "Kalman Filter: A statistical state estimator used in advanced autopilots (ArduPilot/PX4) to optimize estimates dynamically."
        ],
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Algorithmic sensor fusion running in real-time embedded software.",
        takeaway: "Sensor fusion gives the autopilot a noise-free, drift-free estimate of drone orientation.",
        simulationRef: "sim-sensor-fusion"
      },
      {
        id: "d3_s4",
        day: 3,
        topic: "Advanced Sensors",
        title: "Barometers, Compass & GPS Navigation Sensors",
        bullets: [
          "Barometer (Pressure Sensor): Measures air pressure changes (pressure drops ~1.2 hPa per 10m). Enables Altitude Hold.",
          "Foam Shielding: Barometers are light-sensitive and airflow-sensitive; they must be covered with open-cell dark foam.",
          "Magnetometer (Compass): Measures Earth's magnetic field vectors to provide true magnetic heading (critical for autonomous flight).",
          "Interference Warning: Compass must be mounted on a mast far away from high-current battery cables and motor magnets.",
          "GNSS / GPS: Locks onto constellations (GPS, Galileo, GLONASS) for 3D position, ground speed, and Return-to-Home."
        ],
        image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Multi-constellation GPS and compass mast enabling precise spatial awareness.",
        takeaway: "A reliable compass calibration is required for GPS navigation without flyaways."
      },
      {
        id: "d3_s5",
        day: 3,
        topic: "Control Theory",
        title: "Understanding Closed-Loop PID Control",
        bullets: [
          "Open Loop vs. Closed Loop: An open loop sends a command without checking the result. A closed loop continuously measures the outcome and corrects errors.",
          "Error Signal: Error = Desired Angle (from Pilot Stick) - Actual Measured Angle (from IMU).",
          "The PID Equation: Total Correction = (P × Error) + (I × Accumulated Error) + (D × Rate of Error Change).",
          "Loop Rate: Calculated 1,000 to 8,000 times every single second (1kHz to 8kHz) on modern flight controllers.",
          "Purpose: Make the drone track the pilot's commands instantly while resisting wind gusts and frame imbalances."
        ],
        image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Microcontroller computing closed-loop PID equations thousands of times per second.",
        takeaway: "PID is the mathematical heart of drone balance and flight stability.",
        simulationRef: "sim-pid-tuner"
      },
      {
        id: "d3_s6",
        day: 3,
        topic: "The P-Term",
        title: "Proportional (P): The Present Muscle",
        bullets: [
          "Role: Generates a corrective force directly proportional to the size of the current error.",
          "Intuition: The further the drone is pushed away from target angle, the harder P pushes back.",
          "P Too Low: Drone feels mushy, slow to respond, and drifts easily in the wind.",
          "P Too High: Drone over-corrects past the target angle, leading to rapid, high-frequency oscillations.",
          "Goal: Increase P until response is crisp, but stop before fast shaking occurs."
        ],
        image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Proportional gain counteracting external disturbances in real time.",
        takeaway: "P-term provides the immediate stiffness and authority of the drone.",
        simulationRef: "sim-pid-tuner"
      },
      {
        id: "d3_s7",
        day: 3,
        topic: "The I-Term",
        title: "Integral (I): The Memory Against Steady Drift",
        bullets: [
          "Role: Integrates (sums up) small persistent errors over time.",
          "The Problem: P-term drops to zero when error is small, allowing constant wind to push the drone off attitude.",
          "The Solution: As long as any offset exists, I-term keeps ramping up correction until the error is eliminated.",
          "I Too Low: Drone cannot hold its attitude in steady wind or with an off-center battery pack.",
          "I Too High: Drone feels stiff and robotic, and exhibits slow, low-frequency wobbles.",
          "Anti-Windup: Modern firmware restricts I accumulation on the ground to prevent sudden launch flips."
        ],
        image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Integral term maintaining steady attitude in persistent crosswinds.",
        takeaway: "I-term holds your flight attitude regardless of wind or center-of-gravity shifts.",
        simulationRef: "sim-pid-tuner"
      },
      {
        id: "d3_s8",
        day: 3,
        topic: "The D-Term",
        title: "Derivative (D): The Shock Absorber",
        bullets: [
          "Role: Looks at how fast the error is changing (the velocity of the tilt).",
          "Intuition: Acts like a shock absorber or brake on a car. Resists rapid motion.",
          "Damping Action: As P rapidly drives the drone back toward level, D pushes in the opposite direction to prevent overshoot.",
          "D Too Low: Drone bounces and overshoots after fast maneuvers.",
          "D Too High: Amplifies high-frequency motor vibrations, causing motors to run burning hot and wasting battery power.",
          "Filter Requirement: D-term always requires software low-pass filtering to block motor noise."
        ],
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800",
        imageCaption: "Derivative damping prevents overshoot during sharp turns and agile flight.",
        takeaway: "D-term dampens overshoot, but too much D causes hot motors from electrical noise.",
        simulationRef: "sim-pid-tuner"
      },
      {
        id: "d3_s9",
        day: 3,
        topic: "Firmware Setup",
        title: "Software Configuration: Modes, Calibrations & Arming",
        bullets: [
          "Configurators: Betaflight for agile manual flight, ArduPilot (Mission Planner) for autonomous missions.",
          "Board Alignment: Ensure the 3D model on screen moves exactly as you move the physical drone in your hands.",
          "Accelerometer Calibration: Place drone on a spirit-leveled flat table before pressing 'Calibrate Accel'.",
          "Arming Switch: Configure a dedicated 2-position switch on your radio for Arm / Disarm.",
          "Flight Modes: Angle Mode (self-level with angle limit), Horizon Mode (self-level with flip capability), Acro Mode (pure rate control)."
        ],
        image: "https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Interactive flight configurator running real-time 3D model orientation.",
        takeaway: "Never arm the drone until the 3D model orientation in software matches the physical craft exactly."
      },
      {
        id: "d3_s10",
        day: 3,
        topic: "Day 3 Summary",
        title: "Day 3 Review: Stability Mastered",
        bullets: [
          "We explored the IMU: Gyroscope (rate) and Accelerometer (gravity vector).",
          "We understood why Complementary and Kalman filters eliminate gyro drift and vibration noise.",
          "We dissected PID tuning: P gives authority, I holds attitude, D prevents bounce.",
          "We learned to configure flight modes and calibrate sensors on level ground.",
          "Tomorrow (Day 4): Autonomous waypoints, Return-to-Home, systematic troubleshooting, and flight law."
        ],
        image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Sensors tuned and stability confirmed. Moving to autonomous flight in Day 4.",
        takeaway: "A well-tuned PID loop delivers effortless, locked-in flight characteristics."
      }
    ]
  },
  day4: {
    title: "Day 4: Navigation Missions, Troubleshooting & Safety Rules",
    subtitle: "Hours 19 – 24: Ground Stations, Waypoint Missions, Fail-Safes, Diagnostics & Regulations",
    slides: [
      {
        id: "d4_s1",
        day: 4,
        topic: "Ground Stations",
        title: "Ground Control Stations (GCS) & Telemetry",
        bullets: [
          "GCS Platforms: Mission Planner, QGroundControl, and Betaflight OSD.",
          "Telemetry Links: 433MHz/915MHz radio modems or Wi-Fi transmitting real-time speed, altitude, battery voltage, and GPS lock to a ground laptop.",
          "Live Telemetry Display: Artificial Horizon, compass rose, battery percentage, remaining flight time, and signal strength (RSSI).",
          "Bidirectional Commands: GCS allows pilots to upload new waypoints and trigger commands mid-flight from kilometers away.",
          "Data Logging: Complete flight trajectories recorded for scientific analysis, mapping, and incident investigation."
        ],
        image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Ground control station monitoring telemetry data and aerial coordinates.",
        takeaway: "Ground control software transforms a manually flown drone into an autonomous robotics platform."
      },
      {
        id: "d4_s2",
        day: 4,
        topic: "Waypoint Missions",
        title: "Planning Autonomous Waypoint Missions",
        bullets: [
          "Waypoint (WP): A 3D coordinate (Latitude, Longitude, Altitude Above Ground) programmed into flight memory.",
          "Mission Sequence: 1. Takeoff to 15m -> 2. Fly to WP1 at 8m/s -> 3. Pause 5 seconds and trigger camera -> 4. WP2 -> 5. Return to Launch.",
          "Grid Survey Patterns: Lawnmower patterns automatically calculated by GCS for aerial photogrammetry and mapping.",
          "Overlap Settings: 70% forward overlap and 60% side overlap ensure high-precision 3D terrain reconstruction.",
          "Terrain Following: Autopilot reads digital elevation models (DEM) to maintain constant height above rolling hills."
        ],
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Autonomous grid survey mission mapped over natural terrain.",
        takeaway: "Autonomous flight enables repeatable, centimeter-accurate industrial inspections.",
        simulationRef: "sim-waypoint-mission"
      },
      {
        id: "d4_s3",
        day: 4,
        topic: "Fail-Safe Systems",
        title: "Fail-Safe Protocols: Preventing Flyaways",
        bullets: [
          "Radio Signal Loss Failsafe: When receiver loses transmitter packets for >0.5 seconds, autopilot executes pre-set fail-safe.",
          "Fail-Safe Options: 1. Land immediately in place; 2. Return-to-Launch (RTL); 3. Drop (racing safety rule).",
          "Battery Low-Voltage Failsafe: 1st warning at 3.5V/cell triggers GCS alert; 2nd warning at 3.3V/cell forces automatic RTL.",
          "GPS Glitch Failsafe: If satellite lock degrades (HDOP > 2.0), drone switches from GPS PosHold to altitude-only manual mode.",
          "Geofencing: Virtual 3D cylinder boundary. Breaching fence triggers immediate hover or return-to-home."
        ],
        image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Autonomous fail-safe return path calculated above terrain obstacles.",
        takeaway: "Fail-safes are your insurance policy against lost aircraft and property damage.",
        simulationRef: "sim-waypoint-mission"
      },
      {
        id: "d4_s4",
        day: 4,
        topic: "Troubleshooting: Flips",
        title: "The 'Flip on Takeoff': Root Causes & Fixes",
        bullets: [
          "Symptom: Drone applies throttle and instantly cartwheels upside down violently.",
          "Root Cause 1: Propellers installed on wrong motors (CW prop on CCW motor or upside down).",
          "Root Cause 2: Motor spin direction reversed (e.g. Motor 1 spinning CCW when software expects CW).",
          "Root Cause 3: Motor channel order incorrect (e.g. Motor 1 soldered to ESC channel 4).",
          "Root Cause 4: Flight Controller board orientation offset (e.g. arrow points left instead of forward).",
          "Rule: Always test motor spin directions in software with PROPELLERS OFF before flight!"
        ],
        image: "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Systematic bench diagnostic checking motor numbering and prop rotations.",
        takeaway: "A takeoff flip is always a software-hardware mismatch, never a pilot error.",
        simulationRef: "sim-troubleshooting"
      },
      {
        id: "d4_s5",
        day: 4,
        topic: "Troubleshooting: Oscillations",
        title: "Diagnosing In-Flight Vibrations & Hot Motors",
        bullets: [
          "Symptom: Drone wobbles rapidly in hover, or motors come down too hot to touch after a 2-minute flight.",
          "Root Cause 1: D-term gain is set too high in PID settings, amplifying high-frequency noise.",
          "Root Cause 2: Mechanical vibration caused by bent propeller blade, unbolted motor, or cracked carbon arm.",
          "Root Cause 3: Flight controller not soft-mounted on silicone grommets, transferring frame vibration into gyro.",
          "Root Cause 4: Digital low-pass filters set too loose, letting motor electrical noise reach PID loops.",
          "Remedy: Lower D-term by 20%, inspect props, and verify rubber vibration mounts."
        ],
        image: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Inspecting propeller balance and motor mount integrity to eliminate gyro noise.",
        takeaway: "Warm motors are normal; hot motors that burn your finger indicate severe gyro noise or D-term saturation.",
        simulationRef: "sim-troubleshooting"
      },
      {
        id: "d4_s6",
        day: 4,
        topic: "Troubleshooting: Compass",
        title: "Diagnosing GPS Drift & 'Toilet-Bowling'",
        bullets: [
          "Symptom: In GPS Position Hold, the drone begins circling in ever-widening circular spirals.",
          "Why it happens: Heading error between Compass and GPS velocity vector creates a continuous circular overshoot.",
          "Electromagnetic Interference (EMI): Massive DC current flowing through battery leads produces magnetic fields that corrupt the magnetometer.",
          "Physical Fix: Mount the GPS/compass module on an elevated mast at least 10cm above the battery and ESC.",
          "Software Fix: Perform full 3D compass calibration away from metallic structures, reinforced concrete, or cell towers."
        ],
        image: "https://images.unsplash.com/photo-1524143986875-3b098d78b363?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "GPS mast elevating magnetic compass away from high-current power cables.",
        takeaway: "Never calibrate your drone's compass indoors or near cars and steel rebar.",
        simulationRef: "sim-troubleshooting"
      },
      {
        id: "d4_s7",
        day: 4,
        topic: "Pre-Flight Checklist",
        title: "The Professional Pre-Flight Safety Checklist",
        bullets: [
          "1. Physical Airframe: Inspect all M3 frame screws, prop locknuts tightened, battery strap double-checked.",
          "2. Clean Lenses & Antennas: Radio antennas positioned at 90° separation away from carbon fiber edges.",
          "3. Transmitter First: Turn on radio transmitter FIRST. Confirm throttle stick is at zero and arm switch is disarmed.",
          "4. Power Connect: Connect LiPo battery. Listen for clean ESC initialization chimes (e.g. 3 beeps + 2 confirmation beeps).",
          "5. GPS HDOP Lock: Confirm at least 10 satellites and HDOP < 1.5 before arming for autonomous missions.",
          "6. Stand Back: Pilot and bystanders maintain minimum 5-meter safety radius before flipping arm switch."
        ],
        image: "https://images.unsplash.com/photo-1521405924368-64c5b84bec60?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Pilot conducting pre-flight radio check and satellite lock verification.",
        takeaway: "Professional pilots never skip the pre-flight checklist, regardless of experience level."
      },
      {
        id: "d4_s8",
        day: 4,
        topic: "Aviation Regulations",
        title: "Aviation Law, Airspace Categories & Flight Limits",
        bullets: [
          "Weight Categories: Nano (<250g), Micro (250g - 2kg), Small (2kg - 25kg), Medium (25kg - 150kg).",
          "Altitude Limit: 400 feet (120 meters) Above Ground Level (AGL) is the universal international safety ceiling.",
          "Visual Line of Sight (VLOS): You must maintain direct unassisted line of sight with the drone at all times.",
          "Airports & Heliports: Strict 5km / 3-mile No-Fly Zone around active aerodromes.",
          "People & Crowds: Flying over non-consenting open-air assemblies of people is strictly prohibited.",
          "Digital Sky & Remote ID: Drones must broadcast digital registration IDs to prevent illicit operations."
        ],
        image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Safe flight conducted strictly within legal visual line of sight and altitude ceilings.",
        takeaway: "Respect airspace laws to safeguard aviation safety and advance drone innovation."
      },
      {
        id: "d4_s9",
        day: 4,
        topic: "Emergency Procedures",
        title: "Field Emergency & Lost Aircraft Recovery",
        bullets: [
          "Emergency Disarm: If a crash is imminent (e.g. tree branch strike), disarm IMMEDIATELY to prevent burning ESCs and motors.",
          "In-Flight Battery Alarm: Land within 60 seconds of low-voltage buzzer sounding—never attempt 'one more flight lap'.",
          "Beeper / Discovery Buzzer: Install an autonomous 105dB buzzer with internal backup battery for locating downed craft in tall grass.",
          "Pilot Debrief: After flight, inspect motor temperatures with your fingers and check LiPo cell voltages with a pocket checker.",
          "Log Review: Download Blackbox or telemetry logs to verify flight performance and vibration levels."
        ],
        image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Field testing kit with battery meters, recovery beepers, and log analysis tools.",
        takeaway: "Swift emergency disarming saves hundreds of dollars in repair costs."
      },
      {
        id: "d4_s10",
        day: 4,
        topic: "Workshop Graduation",
        title: "Workshop Capstone Review & Certification",
        bullets: [
          "Day 1: Mastered aerodynamics, torque cancellation, BLDC motors, and LiPo voltage safety.",
          "Day 2: Calculated thrust-to-weight ratios, soldered power rails, and executed smoke stopper checks.",
          "Day 3: Understood IMU sensor fusion, configured closed-loop PID control, and calibrated flight boards.",
          "Day 4: Programmed autonomous waypoints, solved complex troubleshooting puzzles, and learned aviation law.",
          "Congratulations! You now have the theoretical foundation and practical skills to design, build, tune, and safely pilot unmanned aerial systems."
        ],
        image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1000&q=80",
        imageCaption: "Workshop complete! Ready to build, configure, and operate UAVs safely.",
        takeaway: "Continuous practice and rigorous safety standards are the hallmarks of a master drone engineer."
      }
    ]
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SLIDES_DATA };
}
